#!/bin/bash

##############################################################################
#                                                                            #
# Copyright 2013 Regents of the University of Michigan                       #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License");            #
#  you may not use this file except in compliance with the License.          #
#  You may obtain a copy of the License at                                   #
#                                                                            #
#      http://www.apache.org/licenses/LICENSE-2.0                            #
#                                                                            #
#  Unless required by applicable law or agreed to in writing, software       #
#  distributed under the License is distributed on an "AS IS" BASIS,         #
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  #
#  See the License for the specific language governing permissions and       #
#  limitations under the License.                                            #
#                                                                            #
##############################################################################


# RPM common setup and functions for all scripts

export PATH=/bin:/usr/bin:/sbin:/usr/java/default/bin:$PATH:.

export version=%%version%%
export release=%%release%%
export username=dicomsvc
export groupname=${username}
export homedir=/usr/local/${username}
export dir_list="/var/log/${username} ${homedir}"
